configName: atsamd21g18a_default
folderName: usb_cdc_dev
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: ATSAMD21G18A
projectName: usb_cdc_dev
settings:
  PackageFilter: bsp;core;core_apps_sam_d21_da1;csp;csp_apps_sam_d21_da1;dev_packs;harmony-services;quick_docs;usb;usb_apps_device
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.6.144\samd21a\atdf\ATSAMD21G18A.atdf
